import type { Team } from './types'

export const TEAMS: Team[] = [
  { id: 'arg', name: 'Argentina', flag: '🇦🇷' },
  { id: 'bra', name: 'Brasil', flag: '🇧🇷' },
  { id: 'uru', name: 'Uruguay', flag: '🇺🇾' },
  { id: 'col', name: 'Colombia', flag: '🇨🇴' },
  { id: 'ven', name: 'Venezuela', flag: '🇻🇪' },
  { id: 'ecu', name: 'Ecuador', flag: '🇪🇨' },
  { id: 'usa', name: 'Estados Unidos', flag: '🇺🇸' },
  { id: 'mex', name: 'Mexico', flag: '🇲🇽' },
  { id: 'can', name: 'Canada', flag: '🇨🇦' },
  { id: 'zaf', name: 'Sudafrica', flag: '🇿🇦' },
  { id: 'cze', name: 'Chequia', flag: '🇨🇿' },
  { id: 'bih', name: 'Bosnia y Herzegovina', flag: '🇧🇦' },
  { id: 'cpv', name: 'Cabo Verde', flag: '🇨🇻' },
  { id: 'civ', name: 'Costa de Marfil', flag: '🇨🇮' },
  { id: 'cod', name: 'RD Congo', flag: '🇨🇩' },
  { id: 'cuw', name: 'Curazao', flag: '🇨🇼' },
  { id: 'hai', name: 'Haiti', flag: '🇭🇹' },
  { id: 'sco', name: 'Escocia', flag: '🏴' },
  { id: 'esp', name: 'España', flag: '🇪🇸' },
  { id: 'fra', name: 'Francia', flag: '🇫🇷' },
  { id: 'eng', name: 'Inglaterra', flag: '🏴' },
  { id: 'por', name: 'Portugal', flag: '🇵🇹' },
  { id: 'ger', name: 'Alemania', flag: '🇩🇪' },
  { id: 'ita', name: 'Italia', flag: '🇮🇹' },
  { id: 'ned', name: 'Paises Bajos', flag: '🇳🇱' },
  { id: 'bel', name: 'Belgica', flag: '🇧🇪' },
  { id: 'cro', name: 'Croacia', flag: '🇭🇷' },
  { id: 'den', name: 'Dinamarca', flag: '🇩🇰' },
  { id: 'jpn', name: 'Japon', flag: '🇯🇵' },
  { id: 'kor', name: 'Corea del Sur', flag: '🇰🇷' },
  { id: 'aus', name: 'Australia', flag: '🇦🇺' },
  { id: 'mar', name: 'Marruecos', flag: '🇲🇦' },
  { id: 'sen', name: 'Senegal', flag: '🇸🇳' },
  { id: 'gha', name: 'Ghana', flag: '🇬🇭' },
  { id: 'cmr', name: 'Camerun', flag: '🇨🇲' },
  { id: 'tun', name: 'Tunez', flag: '🇹🇳' },
  { id: 'nig', name: 'Nigeria', flag: '🇳🇬' },
  { id: 'egy', name: 'Egipto', flag: '🇪🇬' },
  { id: 'srb', name: 'Serbia', flag: '🇷🇸' },
  { id: 'sui', name: 'Suiza', flag: '🇨🇭' },
  { id: 'pol', name: 'Polonia', flag: '🇵🇱' },
  { id: 'aut', name: 'Austria', flag: '🇦🇹' },
  { id: 'swe', name: 'Suecia', flag: '🇸🇪' },
  { id: 'nor', name: 'Noruega', flag: '🇳🇴' },
  { id: 'ukr', name: 'Ucrania', flag: '🇺🇦' },
  { id: 'tur', name: 'Turquia', flag: '🇹🇷' },
  { id: 'gre', name: 'Grecia', flag: '🇬🇷' },
  { id: 'irn', name: 'Iran', flag: '🇮🇷' },
  { id: 'irq', name: 'Irak', flag: '🇮🇶' },
  { id: 'jor', name: 'Jordania', flag: '🇯🇴' },
  { id: 'ksa', name: 'Arabia Saudita', flag: '🇸🇦' },
  { id: 'qat', name: 'Qatar', flag: '🇶🇦' },
  { id: 'alg', name: 'Argelia', flag: '🇩🇿' },
  { id: 'nzl', name: 'Nueva Zelanda', flag: '🇳🇿' },
  { id: 'pan', name: 'Panama', flag: '🇵🇦' },
  { id: 'per', name: 'Peru', flag: '🇵🇪' },
  { id: 'chi', name: 'Chile', flag: '🇨🇱' },
  { id: 'par', name: 'Paraguay', flag: '🇵🇾' },
  { id: 'bol', name: 'Bolivia', flag: '🇧🇴' },
  { id: 'crc', name: 'Costa Rica', flag: '🇨🇷' },
  { id: 'uzb', name: 'Uzbekistan', flag: '🇺🇿' },
]

export function getTeam(teamId: string): Team {
  return (
    TEAMS.find((team) => team.id === teamId) ?? {
      id: teamId,
      name: `Desconocido (${teamId})`,
      flag: '🏳️',
    }
  )
}
