import type { Team } from './types'

export const TEAMS: Team[] = [
  { id: 'mex', name: 'Mexico', flag: '🇲🇽' },
  { id: 'zaf', name: 'South Africa', flag: '🇿🇦' },
  { id: 'kor', name: 'South Korea', flag: '🇰🇷' },
  { id: 'cze', name: 'Czech Republic', flag: '🇨🇿' },
  { id: 'can', name: 'Canada', flag: '🇨🇦' },
  { id: 'bih', name: 'Bosnia & Herzegovina', flag: '🇧🇦' },
  { id: 'qat', name: 'Qatar', flag: '🇶🇦' },
  { id: 'sui', name: 'Switzerland', flag: '🇨🇭' },
  { id: 'bra', name: 'Brazil', flag: '🇧🇷' },
  { id: 'mar', name: 'Morocco', flag: '🇲🇦' },
  { id: 'hai', name: 'Haiti', flag: '🇭🇹' },
  { id: 'sco', name: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { id: 'usa', name: 'USA', flag: '🇺🇸' },
  { id: 'par', name: 'Paraguay', flag: '🇵🇾' },
  { id: 'aus', name: 'Australia', flag: '🇦🇺' },
  { id: 'tur', name: 'Turkey', flag: '🇹🇷' },
  { id: 'ger', name: 'Germany', flag: '🇩🇪' },
  { id: 'cuw', name: 'Curaçao', flag: '🇨🇼' },
  { id: 'civ', name: 'Ivory Coast', flag: '🇨🇮' },
  { id: 'ecu', name: 'Ecuador', flag: '🇪🇨' },
  { id: 'ned', name: 'Netherlands', flag: '🇳🇱' },
  { id: 'jpn', name: 'Japan', flag: '🇯🇵' },
  { id: 'swe', name: 'Sweden', flag: '🇸🇪' },
  { id: 'tun', name: 'Tunisia', flag: '🇹🇳' },
  { id: 'bel', name: 'Belgium', flag: '🇧🇪' },
  { id: 'egy', name: 'Egypt', flag: '🇪🇬' },
  { id: 'irn', name: 'Iran', flag: '🇮🇷' },
  { id: 'nzl', name: 'New Zealand', flag: '🇳🇿' },
  { id: 'esp', name: 'Spain', flag: '🇪🇸' },
  { id: 'cpv', name: 'Cape Verde', flag: '🇨🇻' },
  { id: 'ksa', name: 'Saudi Arabia', flag: '🇸🇦' },
  { id: 'uru', name: 'Uruguay', flag: '🇺🇾' },
  { id: 'fra', name: 'France', flag: '🇫🇷' },
  { id: 'sen', name: 'Senegal', flag: '🇸🇳' },
  { id: 'irq', name: 'Iraq', flag: '🇮🇶' },
  { id: 'nor', name: 'Norway', flag: '🇳🇴' },
  { id: 'arg', name: 'Argentina', flag: '🇦🇷' },
  { id: 'alg', name: 'Algeria', flag: '🇩🇿' },
  { id: 'aut', name: 'Austria', flag: '🇦🇹' },
  { id: 'jor', name: 'Jordan', flag: '🇯🇴' },
  { id: 'por', name: 'Portugal', flag: '🇵🇹' },
  { id: 'cod', name: 'DR Congo', flag: '🇨🇩' },
  { id: 'uzb', name: 'Uzbekistan', flag: '🇺🇿' },
  { id: 'col', name: 'Colombia', flag: '🇨🇴' },
  { id: 'eng', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { id: 'cro', name: 'Croatia', flag: '🇭🇷' },
  { id: 'gha', name: 'Ghana', flag: '🇬🇭' },
  { id: 'pan', name: 'Panama', flag: '🇵🇦' },
]

export function getTeam(teamId: string): Team {
  return (
    TEAMS.find((team) => team.id === teamId) ?? {
      id: teamId,
      name: `Desconocido (${teamId})`,
      flag: '🏳️',
    }
  )
}
