/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as QuinielaRouteImport } from './routes/quiniela'
import { Route as PosicionesRouteImport } from './routes/posiciones'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IngresoRouteImport } from './routes/ingreso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const QuinielaRoute = QuinielaRouteImport.update({
  id: '/quiniela',
  path: '/quiniela',
  getParentRoute: () => rootRouteImport,
} as any)
const PosicionesRoute = PosicionesRouteImport.update({
  id: '/posiciones',
  path: '/posiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoRoute = IngresoRouteImport.update({
  id: '/ingreso',
  path: '/ingreso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ingreso': typeof IngresoRoute
  '/onboarding': typeof OnboardingRoute
  '/posiciones': typeof PosicionesRoute
  '/quiniela': typeof QuinielaRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ingreso': typeof IngresoRoute
  '/onboarding': typeof OnboardingRoute
  '/posiciones': typeof PosicionesRoute
  '/quiniela': typeof QuinielaRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ingreso': typeof IngresoRoute
  '/onboarding': typeof OnboardingRoute
  '/posiciones': typeof PosicionesRoute
  '/quiniela': typeof QuinielaRoute
  '/resultados': typeof ResultadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ingreso'
    | '/onboarding'
    | '/posiciones'
    | '/quiniela'
    | '/resultados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ingreso'
    | '/onboarding'
    | '/posiciones'
    | '/quiniela'
    | '/resultados'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ingreso'
    | '/onboarding'
    | '/posiciones'
    | '/quiniela'
    | '/resultados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  IngresoRoute: typeof IngresoRoute
  OnboardingRoute: typeof OnboardingRoute
  PosicionesRoute: typeof PosicionesRoute
  QuinielaRoute: typeof QuinielaRoute
  ResultadosRoute: typeof ResultadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiniela': {
      id: '/quiniela'
      path: '/quiniela'
      fullPath: '/quiniela'
      preLoaderRoute: typeof QuinielaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posiciones': {
      id: '/posiciones'
      path: '/posiciones'
      fullPath: '/posiciones'
      preLoaderRoute: typeof PosicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso': {
      id: '/ingreso'
      path: '/ingreso'
      fullPath: '/ingreso'
      preLoaderRoute: typeof IngresoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  IngresoRoute: IngresoRoute,
  OnboardingRoute: OnboardingRoute,
  PosicionesRoute: PosicionesRoute,
  QuinielaRoute: QuinielaRoute,
  ResultadosRoute: ResultadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
